### ISSUE TITLE
Discovering this repository

### ISSUE THREAD

**Issue by acresp** [lmelon/homebridge-vaillant-vrc700#1]
Hello,
I'm discovering this repository and I'll own soon a vaillant gaz with vrc700.
Are you working on a homebridge plugin for it ?
Kind regards

**Comment by lmelon** [comment]
I have an implementation for the VR900 (was more logical to name it after the internet gateway).
It is not so well documented and the code would deserve some cleanup and restructuring (it is my first home bridge plugin).

It is based on a reverse engineering of the API used by the android APP.
A bit bleeding edge ... but I use it in my home on a daily basis.

**Comment by acresp** [comment]
Do you think you could share it ? I will probably have the VR920 internet gateway, you think it is the same as the VR900 ? Thank for your work

**Comment by lmelon** [comment]
Have a look here: https://github.com/lmelon/homebridge-vaillant-vrc9xx
